#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v lvim)" ] && alias vim="lvim" vimdiff="lvim -d" && EDITOR='lvim'

# sudo not required for some system commands
for command in yum mount umount sv dnf updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
}

mkcd() {
    mkdir -p "$1"
    cd "$1"
}

goto() {
    cd $1 || zoxide $1
}

e() {
    if [[ -n $1 ]]; then 
        file=$(fd --type file . $1 | fzf)
    else
        file=$(fd --type file | fzf)
    fi
    [[ -n $file ]] && $EDITOR $file
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
    rm="rm -vI" \
	mkd="mkdir -pv" \

# Colorize commands when possible.
alias \
	ls="eza --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
    cat="bat -p" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	lg="lazygit" \
	sdn="shutdown -h now" \
	v="$EDITOR" \
	z="zoxide" \
    tm="tmux attach || tmux new-session"

# Replace ls with eza
# alias \
#     ll="eza -l --icons" \
#     la="eza -Ga --icons" \
#     lt="eza -lT --icons" \
#     lta="eza -lTa --icons" \
#     l="eza -l --icons"


alias \
    ll="eza -l" \
    la="eza -Ga" \
    lt="eza -lT" \
    lta="eza -lTa" \
