#!/bin/sh

waybar_id=$(pidof waybar)
theme="$(cat "$HOME/.cache/theme")"

if [[ $waybar_id ]]; then
    killall waybar
    break
else
    waybar -c "$HOME/.config/waybar/$theme/config.jsonc" -s "$HOME/.config/waybar/$theme/style.css" &
fi
