#!/usr/bin/env bash

wallpaperdir="$HOME/.local/wallpapers/$(cat $HOME/.cache/wallpaperdir)"

while true; do
  wallpaper=$(find $wallpaperdir -type f | shuf -n 1)
  $HOME/.local/bin/swww img $wallpaper --transition-type wipe --transition-angle 30 --transition-step 90 --transition-fps 60
  rm $HOME/.cache/wallpaper.png
  ln -s "$wallpaper" $HOME/.cache/wallpaper.png
  echo "$wallpaper" > $HOME/.cache/wallpaper
  sleep 18m 
done
sleep 1m
