#!/bin/bash

## Kill few processes before their respawn, on a refresh of the Window Manager
## This will prevent multiple instances to run after refresh takes place
## You can grep multiple processes using this script and kill them 

#-- Kill Background-Changer --#
for script in $(ps -ax | grep 'background-changer' | grep -v grep | grep -v vim | awk '{print $1}'); do 
    kill $script 
done  

for i in $(ps -ax | grep 'sleep 8m' | grep -v grep | grep -v vim | awk '{print $1}'); do 
    kill $i
done  

#-- Now freshly start the process in the background --#
bash ~/.config/system_scripts/background-changer &


#-- You can add multiple processes here to prevent their respawns --#
