#!/bin/sh

themedir="$HOME/.config/hypr/themes"
# rice=$(ls $themedir | wofi -i -d) || exit
# rice=$(ls $themedir | rofi -dmenu -i) || exit
rice=$(ls $themedir | tofi --prompt-text="rice: ") || exit
[[ -d $themedir/$rice ]] || exit

echo $rice > $HOME/.cache/rice

killall waybar toggle_waybar

# wallpaper
wallpaperdir="normal"
[[ -d $HOME/.local/wallpapers/$rice ]] && wallpaperdir=$rice

# starship
starshipdir="default"
[[ -d $HOME/.config/starship/themes/$rice ]] && starshipdir=$rice

# kitty
kittydir="default"
[[ -d $HOME/.config/kitty/themes/$rice ]] && kittydir=$rice

wofidir="default"
[[ -d $HOME/.config/wofi/themes/$rice ]] && wofidir=$rice

# lvim colors
lvimthemeconf="$HOME/.config/lvim/lua/user/theme.lua"
lvimtheme="tokyonight"
case $rice in
    gruvbox)
        lvimtheme="gruvbox-material"
        ;;
    axenide)
        lvimtheme="gruvbox-material"
        ;;
    oglo)
        lvimtheme="bamboo"
        ;;
    1amSimple)
        lvimtheme="lunar" 
        wallpaperdir="oglo"
        ;;
    notwidow)
        lvimtheme="catppuccin-frappe"
        ;;
    RUNFUNRUN)
        lvimtheme="kanagawa"
        ;;
    Sakura)
        lvimtheme="catppuccin-mocha"
        ;;
    everforest)
        lvimtheme="everforest"
        wofidir="oglo"
        ;;
    XNM1)
        wofidir="oglo"
        ;;
    *)
        lvimtheme="tokyonight"
        ;;
esac

# apply
echo "lvim.colorscheme = \"$lvimtheme\"" > $lvimthemeconf 
echo $wallpaperdir > $HOME/.cache/wallpaperdir
ln -sf $HOME/.config/hypr/themes/${rice}/theme.conf $HOME/.config/hypr/theme.conf
ln -sf $HOME/.config/starship/themes/${starshipdir}/starship.toml $HOME/.config/starship/starship.toml
ln -sf $HOME/.config/kitty/themes/${kittydir}/theme.conf $HOME/.config/kitty/theme.conf

ln -sf $HOME/.config/wofi/themes/${wofidir}/style.css $HOME/.config/wofi

sleep 0.2

sh $HOME/.config/system_scripts/toggle_waybar
hyprctl reload
sh $HOME/.config/system_scripts/pkill_bc
