#!/bin/sh

themedir="$HOME/.config/hypr/themes"
rice=$(ls $themedir | wofi -i --show dmenu) || exit

echo $rice > $HOME/.cache/rice

killall waybar toggle_waybar

# wallpaper
wallpaperdir="normal"
[[ -d $HOME/.local/wallpapers/$rice ]] && wallpaperdir=$rice

## map different rices to different wallpaper directories
[[ $rice == "1amSimple" ]] && wallpaperdir="oglo"

echo $wallpaperdir > $HOME/.cache/wallpaperdir

# hyprland
ln -f $HOME/.config/hypr/themes/${rice}/theme.conf $HOME/.config/hypr/theme.conf

# starship
starshipdir="oglo"
[[ -d $HOME/.config/starship/themes/$rice ]] && starshipdir=$rice
ln -f $HOME/.config/starship/themes/${starshipdir}/starship.toml $HOME/.config/starship/starship.toml

# kitty
kittydir="default"
[[ -d $HOME/.config/kitty/themes/$rice ]] && kittydir=$rice
ln -f $HOME/.config/kitty/themes/${kittydir}/theme.conf $HOME/.config/kitty/theme.conf

# lvim colors
lvimthemeconf="$HOME/.config/lvim/lua/user/theme.lua"
case $rice in
    gruvbox)
        theme="gruvbox" ;;
    axenide)
        theme="gruvbox" ;;
    oglo)
        theme="gruvbox" ;;
    *)
        theme="tokyonight" ;;
esac
echo "lvim.colorscheme = \"$theme\"" > $lvimthemeconf 

sleep 0.2

sh $HOME/.config/system_scripts/pkill_bc
sh $HOME/.config/system_scripts/toggle_waybar
hyprctl reload
