#!/bin/sh

# WIP

# auto starting apps
wlr-randr --output eDP-1 --scale 1.75 
# wlr-randr --output eDP-1 --scale 2
killall -q swaync swayidle swww swww-daemon waybar dunst nm-applet swayidle blueman-applet
waybar -c $HOME/.config/waybar/hyprdots/config.jsonc -s $HOME/.config/waybar/hyprdots/style.css &
dunst &
# swaync &
$HOME/.local/bin/swww-daemon &
sh ~/.config/system_scripts/pkill_bc &
nm-applet --indicator &
blueman-applet &
swayidle -w timeout 10 ./wayland_session_lock &
# hyprctl plugin load $HOME/.config/hypr/scripts/split-monitor-workspaces.so
