#!/bin/sh

# auto starting apps
wlr-randr --output eDP-1 --scale 1.75 
killall -q spotifyd powerdevil plasma-workspace swaync swayidle swww dunst swww-daemon waybar swaync nm-applet swayidle blueman-applet xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-hyprland xdg-desktop-portal-kde


/usr/libexec/xdg-desktop-portal-hyprland &
sleep 0.5
/usr/lib/xdg-desktop-portal &

$HOME/.local/bin/swww-daemon &
swaync &
sh ~/.config/system_scripts/toggle_waybar &
sh ~/.config/system_scripts/background-changer &
nm-applet --indicator &
blueman-applet &
swayidle -w timeout 10 ./wayland_session_lock &
spotifyd
wal -R
