#!/bin/bash

# Define a function to list Tmux sessions
list_tmux_sessions() {
    tmux list-sessions -F "#{session_name}" | grep -v "scratch"
}

# Check if there are any Tmux sessions
if [ -z "$(list_tmux_sessions)" ]; then
    # If no sessions are active, create a new session
    tmux new-session -d -s default
    session="default"
elif [ "$(list_tmux_sessions | wc -l)" -eq 1 ]; then
    # If there's only one active session, automatically attach to it
    session="$(list_tmux_sessions)"
    tmux attach-session -t "$session"
else
    # If multiple sessions are active, use `wofi` to select a session
    # selected_session="$(list_tmux_sessions | wofi --dmenu -i -p "Select a Tmux session:")"
    selected_session="$(list_tmux_sessions | tofi --prompt-text="Session:")"

    # Check if the user canceled session selection
    if [ -z "$selected_session" ]; then
        exit 0
    else
        session="$selected_session"
        tmux attach-session -t "$session"
    fi
fi

if [ -n "$1" ]; then
    kitty tmux new-session -A -s "$session" -d "$1"
else
    # Launch Kitty with the selected Tmux session
    kitty tmux new-session -A -s "$session"
fi
