#!/bin/sh

NOTMUCH_CONFIG="$HOME/.config/notmuch/config"
HSTSIZE=100000
SAVEHIST=100000
HIST_STAMPS="dd/mm/yyyy"
HISTFILE="${XDG_CONFIG_HOME:-$HOME/.cache}/zsh/history"
LESSHISTFILE="${XDG_CONFIG_HOME:-$HOME/.cache}/less/history"

MANPAGER="batman"
TERM="xterm-256color"

BUN_INSTALL="$HOME/.local/share/bun"
[ -d "$BUN_INSTALL/bin" ] && export PATH="$PATH:$BUN_INSTALL/bin"

[ -d "$HOME/.local/bin" ] && export PATH="$PATH:$HOME/.local/bin"
[ -d "$HOME/.cargo/bin" ] && export PATH="$PATH:$HOME/.cargo/bin"
[ -d "$HOME/go/bin" ] && export PATH="$PATH:$HOME/go/bin"
[ -d "$HOME/.config/emacs/bin" ] && export PATH="$PATH:$HOME/.config/emacs/bin"

# bun completions
[ -s "$BUN_INSTALL/_bun" ] && source "$BUN_INSTALL/_bun"
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # lets you tab complete hidden files by default

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bindsrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bindsrc"
