#!/bin/sh

NOTMUCH_CONFIG="$HOME/.config/notmuch/config"
HSTSIZE=100000
SAVEHIST=100000
HIST_STAMPS="dd/mm/yyyy"
HISTFILE="${XDG_CONFIG_HOME:-$HOME/.cache}/zsh/history"
LESSHISTFILE="${XDG_CONFIG_HOME:-$HOME/.cache}/less/history"

export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml

shadafile="$HOME/.config/vim/viminfo"

MANPAGER="batman"

BUN_INSTALL="$HOME/.local/share/bun"
[ -d "$BUN_INSTALL/bin" ] && export PATH="$PATH:$BUN_INSTALL/bin"

[ -d "$HOME/.local/bin" ] && export PATH="$PATH:$HOME/.local/bin"
[ -d "$HOME/.cargo/bin" ] && export PATH="$PATH:$HOME/.cargo/bin"
[ -d "$HOME/go/bin" ] && export PATH="$PATH:$HOME/go/bin"
[ -d "$HOME/.config/emacs/bin" ] && export PATH="$PATH:$HOME/.config/emacs/bin"

# bun completions
[ -s "$BUN_INSTALL/_bun" ] && source "$BUN_INSTALL/_bun"

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bindsrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bindsrc"
