autoload -U colors && colors
setopt autocd
stty stop undef
setopt interactive_comments

HISTSIZE=100000
SAVEHIST=100000
HIST_STAMPS="dd/mm/yyyy"
HISTFILE="${XDG_CONFIG_HOME:-$HOME/.cache}/zsh/history"

BUN_INSTALL="$HOME/.local/share/bun"
export TERM="xterm-256color"
[ -d "$BUN_INSTALL/bin" ] && export PATH="$PATH:$BUN_INSTALL/bin"

[ -d "$HOME/.local/bin" ] && export PATH="$PATH:$HOME/.local/bin"
[ -d "$HOME/.cargo/bin" ] && export PATH="$PATH:$HOME/.cargo/bin"

# export MANPAGER="sh -c 'col -bx | bat -l man -p'"

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bindsrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bindsrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env"

# bun completions
[ -s "$BUN_INSTALL/_bun" ] && source "$BUN_INSTALL/_bun"
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # lets you tab complete hidden files by default

# Plugins
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2> /dev/null
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh 2> /dev/null
source /usr/share/fzf/shell/key-bindings.zsh 2> /dev/null

greet
